# ========================================
# API网关配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8092

spring:
  application:
    # 应用名称
    name: api-gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
    gateway:
      routes:
        # 订单服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order-service/**
          filters:
            - StripPrefix=2

        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2

        # 库存服务路由
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory-service/**
          filters:
            - StripPrefix=2

        # 邮件服务路由
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email-service/**
          filters:
            - StripPrefix=2

        # 日志服务路由
        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/api/log-service/**
          filters:
            - StripPrefix=2

      # 全局过滤器
      default-filters:
        # 添加请求头
        - AddRequestHeader=X-Forwarded-By, api-gateway
        # 添加响应头
        - AddResponseHeader=X-Response-By, api-gateway
      
      # 禁用grpc相关功能以避免依赖问题
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

# 日志级别配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.apache.rocketmq: WARN