# ========================================
# 共享模块配置文件
# @author BruceXuK
# ========================================

rocketmq:
  # NameServer地址
  name-server: ${ROCKETMQ_NAMESRV_ADDR:localhost:9876}
  # 生产者配置
  producer:
    # 生产者组
    group: shared-log-producer
    # 消息发送超时时间(毫秒)
    send-message-timeout: 10000
    # 消息发送失败重试次数
    retry-times-when-send-failed: 3
  # 消费者配置
  consumer:
    # 消费者启动失败重试次数
    retry-times: 3
    # 消费者启动延迟时间(毫秒)
    delay-time: 5000
    # 启用延迟加载，避免启动时立即连接MQ
    enable-msg-trace: false
    customized-trace-topic: 

# 全局配置RocketMQ自动重试
spring:
  autoconfigure:
    exclude: org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration