# ========================================
# 用户服务配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8084

spring:
  # 应用配置
  application:
    # 应用名称
    name: user-service

# RocketMQ配置
rocketmq:
  # NameServer地址
  name-server: ${ROCKETMQ_NAMESRV_ADDR:localhost:9876}
  # 生产者配置
  producer:
    # 生产者组
    group: user-service-producer
    # 消息发送超时时间(毫秒)
    send-message-timeout: 10000
    # 消息发送失败重试次数
    retry-times-when-send-failed: 3
  # 消费者配置
  consumer:
    # 消费者启动失败重试次数
    retry-times: 3
    # 消费者启动延迟时间(毫秒)
    delay-time: 5000

# Actuator监控配置
management:
  endpoints:
    web:
      # 暴露所有端点
      exposure:
        include: "*"

# 日志配置
logging:
  level:
    # 根日志级别
    root: INFO
    # 项目日志级别
    com.bruce.mq: DEBUG
    org.apache.rocketmq: WARN
  # 日志格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"