# ========================================
# 用户服务配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8084

spring:
  # 应用配置
  application:
    # 应用名称
    name: user-service

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

# RocketMQ配置
rocketmq:
  # 是否启用RocketMQ
  enable: true
  # NameServer地址
  name-server: ${ROCKETMQ_NAMESRV_ADDR:localhost:9876}
  # 生产者配置
  producer:
    # 生产者组
    group: user-service-producer
    # 消息发送超时时间(毫秒)
    send-message-timeout: 3000
    # 消息发送失败重试次数
    retry-times-when-send-failed: 2
    # 异步消息发送失败重试次数
    retry-times-when-send-async: 2
  # 消费者配置
  consumer:
    # 消费者启动失败重试次数
    retry-times: 0
    # 消费者启动延迟时间(毫秒)
    delay-time: 5000

# 日志级别配置
logging:
  level:
    # 根日志级别
    root: INFO
    # 项目日志级别
    com.bruce.mq: DEBUG
    org.apache.rocketmq: WARN