# ========================================
# 用户服务配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8084

spring:
  # 应用配置
  application:
    # 应用名称
    name: user-service

# RocketMQ配置
rocketmq:
  # NameServer地址
  name-server: localhost:9876
  producer:
      group: user-service-producer
      # 发送超时时间（毫秒）
      send-message-timeout: 3000
      # 消息压缩阈值（字节）
      compress-over-howmuch-body-currently-hold: 1024
      # 同步发送失败重试次数
      retry-times-when-send-failed: 2
      # 异步发送失败重试次数
      retry-times-when-send-async-failed: 2

# Actuator监控配置
management:
  endpoints:
    web:
      # 暴露所有端点
      exposure:
        include: "*"

# 日志配置
logging:
  level:
    # 根日志级别
    root: INFO
    # 项目日志级别
    com.bruce.mq: DEBUG
  # 日志格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
