# ========================================
# 订单服务配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8085

spring:
  # 应用配置
  application:
    # 应用名称
    name: order-service

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
# RocketMQ配置
rocketmq:
  # NameServer地址
  name-server: ${ROCKETMQ_NAMESRV_ADDR:localhost:9876}
  # 生产者配置
  producer:
    # 生产者组
    group: order-producer-group
  # 消费者配置
  consumer:
    # 消费者启动失败重试次数
    retry-times: 3
    # 消费者启动延迟时间(毫秒)
    delay-time: 5000

# API网关配置
gateway:
  # API网关URL
  url: http://localhost:8092

# 应用自定义配置
app:
  # 邮件管理员配置
  mail:
    admin:
      # 管理员邮箱地址
      email-address: ${ADMIN_EMAIL_ADDRESS:customer@example.com}

email:
  default_to_address: ${DEFAULT_EMAIL_ADDRESS:customer@example.com}

# Actuator监控配置
management:
  endpoints:
    web:
      # 暴露所有端点
      exposure:
        include: "*"

# 日志级别配置
logging:
  level:
    com.bruce.mq.order: DEBUG
    org.apache.rocketmq: WARN
