# ========================================
# 日志服务配置文件
# ========================================

server:
  # 服务器端口
  port: 8091

spring:
  # 应用配置
  application:
    # 应用名称
    name: log-service

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

  # Elasticsearch配置
  elasticsearch:
    uris: ${ES_URI:http://localhost:9200}
    username: ${ES_USERNAME:}
    password: ${ES_PASSWORD:}

  # 日志配置
  output:
    ansi:
      enabled: ALWAYS

# RocketMQ配置
rocketmq:
  # 是否启用RocketMQ，设置为false时不会在启动时连接MQ
  enable: false
  # NameServer地址
  name-server: ${ROCKETMQ_NAMESRV_ADDR:localhost:9876}
  # 消费者配置
  consumer:
    # 消费者启动失败重试次数
    retry-times: 0
    # 消费者启动延迟时间(毫秒)
    delay-time: 5000

# 日志级别配置
logging:
  level:
    com.bruce.mq.log: DEBUG
    org.apache.rocketmq: WARN