# ========================================
# 库存服务配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8083

spring:
  # 应用配置
  application:
    # 应用名称
    name: inventory-service
  
  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
# RocketMQ配置
rocketmq:
  # NameServer地址
  name-server: ${ROCKETMQ_NAMESRV_ADDR:localhost:9876}

# API网关配置
gateway:
  # API网关URL
  url: http://localhost:8092

# 应用自定义配置
app:
  # 邮件管理员配置
  mail:
    admin:
      # 管理员邮箱地址
      email-address: ${ADMIN_EMAIL_ADDRESS:your_email_address@qq.com}

# Actuator监控配置
management:
  endpoints:
    web:
      # 暴露所有端点
      exposure:
        include: "*"

# 日志级别配置
logging:
  level:
    com.bruce.mq.inventory: DEBUG
    org.apache.rocketmq: WARN
