# ========================================
# 库存服务配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8086

spring:
  # 应用配置
  application:
    # 应用名称
    name: inventory-service

# RocketMQ配置
rocketmq:
  # NameServer地址
  name-server: localhost:9876

# Actuator监控配置
management:
  endpoints:
    web:
      # 暴露所有端点
      exposure:
        include: "*"

# 日志配置
logging:
  level:
    # RocketMQ日志级别
    org.apache.rocketmq: DEBUG
    # 项目日志级别
    com.bruce.mq: DEBUG