# ========================================
# 邮件服务配置文件
# @author BruceXuK
# ========================================

server:
  # 服务器端口
  port: 8088

spring:
  # 应用配置
  application:
    # 应用名称
    name: email-service

  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  # 邮件配置
  mail:
    # 邮件服务器主机
    host: ${MAIL_HOST:smtp.gmail.com}
    # 邮件服务器端口
    port: ${MAIL_PORT:465}
    # 邮箱用户名
    username: ${MAIL_USERNAME:your_email@gmail.com}
    # 邮箱密码
    password: ${MAIL_PASSWORD:your_password}
    # 邮件属性配置
    properties:
      mail:
        smtp:
          # SMTP认证
          auth: true
          # STARTTLS加密
          starttls:
            enable: true
  # 日志配置
  output:
    ansi:
      enabled: ALWAYS
# RocketMQ配置
rocketmq:
  # NameServer地址
  name-server: ${ROCKETMQ_NAMESRV_ADDR:localhost:9876}
  # 生产者配置
  producer:
    # 生产者组
    group: email-service-producer
    # 消息发送超时时间(毫秒)
    send-message-timeout: 3000
    # 消息发送失败重试次数
    retry-times-when-send-failed: 2
    # 异步消息发送失败重试次数
    retry-times-when-send-async: 2
  # 消费者配置
  consumer:
    # 消费者启动失败重试次数
    retry-times: 0
    # 消费者启动延迟时间(毫秒)
    delay-time: 5000

# 应用自定义配置
app:
  # 邮件管理员配置
  mail:
    admin:
      # 管理员邮箱地址
      email-address: ${ADMIN_EMAIL_ADDRESS:your_email@gmail.com}

# 日志级别配置
logging:
  level:
    com.bruce.mq.email: DEBUG
    org.apache.rocketmq: WARN
